import sys
reload(sys)
sys.setdefaultencoding("latin-1")

import xlrd, arcpy, string, os, zipfile, fileinput, time
from datetime import date
start_time = time.time()

INPUT_PATH = "input"
OUTPUT_PATH = "output"
if arcpy.Exists(OUTPUT_PATH + "\\LandFill.gdb"):
	os.system("rmdir " + OUTPUT_PATH + "\\LandFill.gdb /s /q")
os.system("del " + OUTPUT_PATH + "\\*LandFill*.*")
arcpy.CreateFileGDB_management(OUTPUT_PATH, "LandFill", "9.3")
arcpy.env.workspace = OUTPUT_PATH + "\\LandFill.gdb"

MOE_MOE_Regions_1KM = "C:\\Users\\yuanje\\Downloads\\SDE\\DSDE_MOE.sde\\MOE.MOE_Regions_1KM"
MOE_LIMO_Landfill_Sites = "C:\\Users\\yuanje\\Downloads\\SDE\\DSDE_MOE.sde\\MOE.LIMO_Landfill_Sites"
arcpy.Project_management(MOE_MOE_Regions_1KM, "MOE_Regions_1KM", "PROJCS['WGS_1984_Web_Mercator_Auxiliary_Sphere',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator_Auxiliary_Sphere'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],PARAMETER['Auxiliary_Sphere_Type',0.0],UNIT['Meter',1.0]]", "WGS_1984_(ITRF00)_To_NAD_1983", "GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433],METADATA['North America - NAD83',167.65,14.93,-47.74,86.45,0.0,0.0174532925199433,0.0,1350]]")
arcpy.Project_management(MOE_LIMO_Landfill_Sites, "LIMO_Landfill_Sites", "PROJCS['WGS_1984_Web_Mercator_Auxiliary_Sphere',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator_Auxiliary_Sphere'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],PARAMETER['Auxiliary_Sphere_Type',0.0],UNIT['Meter',1.0]]", "WGS_1984_(ITRF00)_To_NAD_1983", "GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433],METADATA['North America - NAD83',167.65,14.93,-47.74,86.45,0.0,0.0174532925199433,0.0,1350]]")
arcpy.SpatialJoin_analysis("LIMO_Landfill_Sites", "MOE_Regions_1KM", "LIMO_Landfill_Sites_MOE_Region", "JOIN_ONE_TO_ONE", "KEEP_ALL", "ID_NO \"ID_NO\" true true false 8 Double 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,ID_NO,-1,-1;SITE_NAME \"SITE_NAME\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,SITE_NAME,-1,-1;STATUS \"STATUS\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,STATUS,-1,-1;ADDRESS \"ADDRESS\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,ADDRESS,-1,-1;MUNICIPALITY \"MUNICIPALITY\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,MUNICIPALITY,-1,-1;LOCATIONTEXT \"LOCATIONTEXT\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,LOCATIONTEXT,-1,-1;PHYSICALPLAN \"PHYSICALPLAN\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,PHYSICALPLAN,-1,-1;TOWNSHIP \"TOWNSHIP\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,TOWNSHIP,-1,-1;COUNTY \"COUNTY\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,COUNTY,-1,-1;LATITUDE \"LATITUDE\" true true false 8 Double 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,LATITUDE,-1,-1;LONGITUDE \"LONGITUDE\" true true false 8 Double 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,LONGITUDE,-1,-1;HYPERLINK \"HYPERLINK\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,HYPERLINK,-1,-1;COFA_NUM \"COFA_NUM\" true true false 20 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,COFA_NUM,-1,-1;SITE_NAME_UPPER \"SITE_NAME_UPPER\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,SITE_NAME_UPPER,-1,-1;TYPE \"TYPE\" true true false 50 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,TYPE,-1,-1;MUNICIPALITY_UPPER \"MUNICIPALITY_UPPER\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,MUNICIPALITY_UPPER,-1,-1;TOWNSHIP_UPPER \"TOWNSHIP_UPPER\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,TOWNSHIP_UPPER,-1,-1;COUNTY_UPPER \"COUNTY_UPPER\" true true false 255 Text 0 0 ,First,#," + arcpy.env.workspace + "\\LIMO_Landfill_Sites,COUNTY_UPPER,-1,-1;MOE_REGION \"MOE_REGION\" true true false 25 Text 0 0 ,First,#," + arcpy.env.workspace + "\\MOE_Regions_1KM,MOE_REGION,-1,-1;SHAPE_Length \"SHAPE_Length\" false true true 8 Double 0 0 ,First,#," + arcpy.env.workspace + "\\MOE_Regions_1KM,SHAPE_Length,-1,-1;SHAPE_Area \"SHAPE_Area\" false true true 8 Double 0 0 ,First,#," + arcpy.env.workspace + "\\MOE_Regions_1KM,SHAPE_Area,-1,-1", "INTERSECT", "", "")
arcpy.Delete_management("LIMO_Landfill_Sites", "FeatureClass")
arcpy.DeleteField_management("LIMO_Landfill_Sites_MOE_Region", "HYPERLINK;Join_Count;TARGET_FID;ID_NO")

elapsed_time = time.time() - start_time
print elapsed_time